### ISSUE TITLE
异常

### ISSUE THREAD

**Issue by youtzz** [xuhongv/XSmartConfig#2]
使用场景：手机是小米8青春版，手机连接的wifi没有联网，app执行配网后直接崩溃，同样的情况下用esptouch可以执行配网，但是无法搜索到设备
I/__EsptouchTask: Welcome Esptouch v0.3.4.6
D/UDPSocketServer: mServerSocket is created, socket read timeout: 60000, port: 18266
D/__EsptouchTask: execute()
I/__EsptouchTask: localInetAddress: /192.168.137.210
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.example.jojo.testonenets, PID: 20962
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at com.xuhong.xsmartconfiglib.util.EspNetUtil.parseBssid2bytes(EspNetUtil.java:86)
        at com.xuhong.xsmartconfiglib.protocol.DatumCode.<init>(DatumCode.java:42)
        at com.xuhong.xsmartconfiglib.protocol.EsptouchGenerator.<init>(EsptouchGenerator.java:41)
        at com.xuhong.xsmartconfiglib.task.__EsptouchTask.executeForResults(__EsptouchTask.java:323)
        at com.xuhong.xsmartconfiglib.EsptouchTask.executeForResults(EsptouchTask.java:95)
        at com.xuhong.xsmartconfiglib.api.xEspTouchTask$IEsp8266TouchTask.doInBackground(xEspTouchTask.java:193)
        at com.xuhong.xsmartconfiglib.api.xEspTouchTask$IEsp8266TouchTask.doInBackground(xEspTouchTask.java:164)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
I/Process: Sending signal. PID: 20962 SIG: 9
Application terminated.

**Comment by xuhongv** [comment]
这个和ap联网是否没有关系呀
